name: First Workflow
on: [push]

env:
  SECRETVALUE: ''

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          inlineScript: |
            SECRET=$(az keyvault secret show --name GitHubSecret --vault-name LlavesGitHub --query value -o tsv)
            echo "::set-output name=secret::$SECRET"
      - name: Use secret in subsequent steps
        run: |
          echo "The secret is ${{ steps.read-secret.outputs.secret }}"