name: First Workflow
on: [push]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name : "Login Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Retrieve secret from KV
        uses: azure/CLI@v1
        with:
          inlineScript: |
            secretValue=$(az keyvault secret show --name "AppDummyApp3" --vault-name "GitHubSecret" --query "value")
            echo "SECRETVALUE="$secretValue >> $GITHUB_ENV