name: First Workflow
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
        enable-AzPSSession: true
    - name: Get secret
        uses: ikumi9/azure-keyvault-action@v1.0.0
        with:
          keyvault: LlavesGithub
          secret: GitHubSecret
        id: get-secret