name: First Workflow
on: [push]

env:
  SECRETVALUE: ''

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          inlineScript: |
            cho SECRETVALUE=$(az keyvault secret show --vault-name LlavesGithub --name GitHubSecret --query value) >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.SECRETVALUE }}"