name: First Workflow
on: [push]

env:
  SECRET: ''

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Read secret from Key Vault
        run: |
          SECRET=$(az keyvault secret show --name GitHubSecret --vault-name LlavesGitHub --query value -o tsv)
          echo "SECRET=$SECRET" >> $GITHUB_ENV
      - name: Use secret in subsequent steps
        run: |
          echo "The secret is $SECRET"