name: First Workflow
on: [push]

jobs:
  run-commands::
    runs-on: ubuntu-latest
    steps:
      - name : "Login Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: echo a string
        run: echo "HELLO WORLD"