name: First Workflow
on: [push]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name : "Login Azure"
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Azure CLI script
        uses: Azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show